let video;
let w = 1300;
let h = 900;
let thresholdVal = 0.30;

let story = `I AM SLOUCHED ON MY BED, AS MY LAPTOP IS BALANCED PRECARIOUSLY ON A PILLOW; THE SCREEN ON MY LAPTOP IS BLINDING ME. “WRITE SOMETHING, YOU COWARD,” MY BRAIN SCREAMS WHILE I TRY TO THINK OF ALL THE POSSIBLE STORIES I COULD WRITE FOR THIS ASSIGNMENT. I LOOK AROUND MYSELF. MY ROOM’S A DISASTER WITH EMPTY COFFEE MUGS, A NOTEBOOK FULL OF DUMB SCRIBBLES, AND A RANDOM RED SOCK THAT’S BEEN LYING ON TOP OF MY LAMP. AS I STARE AT MY SCREEN, OUT OF NOWHERE, I GET THIS IDEA: WHAT IF I WRITE A STORY ABOUT WRITING THIS STORY? WILD, RIGHT? “YEAH, WOW, HOW COULD I EVEN THINK OF SUCH A COOL THING THAT HAS NEVER BEEN DONE BEFORE?” MY MIND MOCKS ME, DRIPPING WITH SARCASM SOOOO THICK THAT IT COULD CHOKE ME. WELL, MY SPECIAL TALENT’S NOT WRITING; IT’S OVERTHINKING. SO LET ME DO THAT ON PAPER. LET’S GET STARTED ON THE CHARACTERS IN THIS STORY. IT WOULD BE ME, OF COURSE, AND I ASSUME YOU, WHOEVER’S READING THIS, ARE PART OF THIS STORY. I MEAN, CAN I EVEN CALL THIS THING A STORY? IT FEELS MORE LIKE A ONE-SIDED CONVERSATION/RANT BY AN INDECISIVE GIRL IN HER 20S WHO CAN’T MAKE UP HER MIND, FOR FUCK’S SAKE. SOMETIMES, CREATING FEELS LIKE HITTING A BRICK WALL, AND RIGHT NOW, I AM BANGING MY HEAD AGAINST THAT WALL IN A NICE REPETITIVE OSCILLATORY MOTION. YET, I CAN’T SEEM TO GET ANY IDEAS. WELL, BURNOUT’S A BITCH. AS I TYPE EVERY SENTENCE, “THIS IS GARBAGE,” MY BRAIN TEASES ME. “A STORY ABOUT A STORY? THAT’S THE DUMBEST, MOST UNORIGINAL SHIT YOU COULD’VE PICKED.” IT IS GETTING PRETTY ANNOYING IN MY HEAD, JUST LIKE THIS STORY RIGHT NOW, BUT I GUESS I’M STUCK WITH THIS META CRAP. WHY CAN’T I WRITE SOMETHING CUTE AND SIMPLE? LIKE A HEARTWARMING LITTLE STORY ABOUT TWO IDIOTS IN A COFFEE SHOP? MY BRAIN STARTS VOMITING IDEAS - THRILLERS, GHOSTS, MAGIC FORESTS, FUTURISTIC CITIES YET I WANT TO WRITE THIS? AHH, I’M SCREWING MYSELF OVER, AND I’M DAMN GOOD AT IT. IT’S GETTING DARKER OUTSIDE, AND MY LAPTOP SWITCHED TO ‘NIGHT MODE.’ I SEE A FAINT REFLECTION ON MY SCREEN; SHE LOOKS CRAZY. LIKE SHE HASN’T SLEPT IN FOREVER. THEN I THINK TO MYSELF, WHAT IF I WRITE A STORY OF HER? ME? MY LIFE? SOMETHING THAT I’VE EXPERIENCED AND LIVED THROUGH? BUT WAIT, IN THE GRAND SCHEME OF THINGS, AND WITH MILLIONS OF PEOPLE IN THE WORLD, I STILL CHOOSE TO TALK ABOUT MYSELF? HOW NARCISSISTIC! WHAT IF I WRITE ABOUT A MAGICAL WORLD? I ASK MYSELF. WHAT MAGICAL WORLD CAN I EVEN FANTASIZE ABOUT AND WRITE A MAKE-BELIEVE STORY, WHEN THE WHOLE WORLD FEELS LIKE IT IS CONSTANTLY BURNING, PEOPLE FACE SO MUCH EVERY DAY, STRUGGLE, AND SURVIVE, WHILE THE GREEDY GET GREEDIER AND THE POWERFUL GET MORE POWERFUL? I SHOULD PROBABLY WRITE ABOUT SOMETHING IMPORTANT. SOMETHING HUGE, SOMETHING THAT HAS AN IMPACT. BUT WHAT CAN BE SAID THAT HAS NOT BEEN SAID BEFORE? WHAT CAN I WRITE WHEN I’M NOT SURE WHAT MY VOICE IS? I’M TERRIBLE AT GETTING MY THOUGHTS OUT OF MY HEAD. I WANT TO MAKE SOMETHING REAL, BUT I KEEP SECOND-GUESSING EVERY WORD. NEVERTHELESS, I NEED TO TRY. TRY AND TRY. TO CREATE. SOMETHING. ANYTHING. BUT THERE’S ALWAYS A LIMIT. A TIME LIMIT. FUCK. THE UNIVERSE IS 13.8 BILLION YEARS OLD WITH GINORMOUS GALAXIES AND BLACK HOLES ON A SCALE WE CAN’T EVEN IMAGINE. AMONG ALL THAT, I’M NOTHING BUT A SPECK OF DUST. STUCK ON A HUGE ROCK. INSIDE FOUR WALLS THAT WE BUILT TO CONTAIN OURSELVES. AND THE SIGNIFICANCE OF MY ASSIGNMENT? MY STORIES? MICROSCOPIC. WHATEVER I WRITE, IT WON’T MATTER. WE ALL PERISH, DON’T WE? JUST FLEETING BLIPS IN THE COSMIC STATIC. WELL NOW, DON’T I SOUND PRETENTIOUSLY DEEP? I AM CRUMBLING UNDER THE INSIGNIFICANCE OF MY WORK AND HOW MUCH IT DOESN’T MATTER IN THE GRAND SCHEME OF THINGS, AND YET, AS I TYPE THIS, IT FEELS LIKE THE WHOLE WORLD IS WATCHING OVER MY SHOULDER, JUDGING MY EVERY CLUMSY PHRASE. IT’S IRRATIONAL, BUT IT’S REAL, THIS PRESSURE TO BE PROFOUND, TO BE HEARD, TO BE SOMETHING. I CHOSE THIS CREATIVE LIFE TO LET MY VOICE BE HEARD, BUT RIGHT NOW IT’S A JUMBLED MESS, BUT I BELIEVE IT WON’T STAY IN THE SAME PLACE FOREVER. JUST LIKE THIS RED SOCK ON MY LAMP. DEAR SOCK, YOU WILL GET WHERE YOU BELONG WHEN IT’S TIME. AND THEN, A SHIFT. I THINK ABOUT YOU! THE READER! MAYBE YOU’RE OUT THERE, FEELING THIS TOO. THE DREAD OF CREATING, THE FEAR THAT YOUR WORK DOESN’T MATTER, THE EXHAUSTION OF TRYING TO FIND YOUR PLACE IN A WORLD THAT’S TOO BIG AND TOO BROKEN. IF YOU CAN FEEL THIS, EVEN FOR A SECOND, THEN WE’RE CONNECTED. WE’RE IN THIS TOGETHER. AND THAT’S THE POINT, ISN’T IT? NOT TO CHANGE THE UNIVERSE, BUT TO REACH ONE PERSON, TO MAKE THEM FEEL LESS ALONE. WE CAN’T ALWAYS DO SHIT, AND THAT’S OKAY. SOMETIMES, JUST SHOWING UP IS ENOUGH. SO, I KEEP WRITING. THIS STORY’S NOT PERFECT. IT’S NOT GROUNDBREAKING. IT’S JUST MINE—RAW, MESSY, HONEST. IT’S A SNAPSHOT OF A GIRL, OVERTHINKING HER WAY THROUGH A BLANK PAGE, TRYING TO MAKE SENSE OF HER PLACE IN THE WORLD. IT’S A REMINDER THAT CREATING IS HARD, BUT IT’S ALSO HUMAN. WE MIGHT JUST BE SPECKS IN THE UNIVERSE, BUT OUR STORIES? THEY’RE THE SPARKS THAT LIGHT UP THE DARK, EVEN IF JUST FOR A MOMENT.`;

let letters = [];
let currentCharIndex = 0;

function setup() {
  createCanvas(w, h);
  video = createCapture(VIDEO);
  video.size(w, h);
  video.hide();
  textFont('Helvetica');
}

function draw() {
  background("#f5f5dc");
  image(video, 0, 0);
  filter(THRESHOLD, thresholdVal);

  for (let i = letters.length - 1; i >= 0; i--) {
    letters[i].update();
    letters[i].display();

    if (letters[i].y > height + 50) {
      letters.splice(i, 1);
    }
  }
}

function mouseMoved() {
  for (let i = 0; i < 1; i++) {
    if (currentCharIndex < story.length) {
      let char = story.charAt(currentCharIndex);
      letters.push(new SpiralLetter(mouseX, mouseY, char));
      currentCharIndex++;
    }
  }
}

class SpiralLetter {
  constructor(baseX, baseY, char) {
    this.baseX = baseX + random(-5, 30);
    this.y = baseY;
    this.radius = random(10, 80);
    this.angle = random(TWO_PI);
    this.speed = random(1, 3);
    this.angleSpeed = random(0.05, 0.15);
    this.char = char.toUpperCase(); // Convert character to uppercase
  }

  update() {
    this.y += this.speed;
    this.angle += this.angleSpeed;
  }

  display() {
    let x = this.baseX + this.radius * cos(this.angle);
    fill("#d10000");
    noStroke();
    textSize(30);
    text(this.char, x, this.y);
  }
}
